# Scala Steward Configuration
# https://github.com/scala-steward-org/scala-steward/blob/main/docs/repo-specific-configuration.md

# Control the frequency of pull requests.
# "7 days" restricts updates to weekly, reducing PR noise.
pullRequests.frequency = "7 days"

# Assign @rabestro as the owner of the PRs.
pullRequests.assignees = [ "rabestro" ]

# Automatically request a review from @rabestro on new PRs.
reviewers = [ "rabestro" ]
